[2022-10-27T14:20:38.966+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T14:01:47.069341+00:00 [queued]>
[2022-10-27T14:20:39.034+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T14:01:47.069341+00:00 [queued]>
[2022-10-27T14:20:39.035+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T14:20:39.035+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 1
[2022-10-27T14:20:39.035+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T14:20:39.169+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): processing_data> on 2022-10-27 14:01:47.069341+00:00
[2022-10-27T14:20:39.189+0000] {standard_task_runner.py:54} INFO - Started process 171 to run task
[2022-10-27T14:20:39.221+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'processing_data', 'manual__2022-10-27T14:01:47.069341+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmppeyk_9t6']
[2022-10-27T14:20:39.223+0000] {standard_task_runner.py:83} INFO - Job 59: Subtask processing_data
[2022-10-27T14:20:39.224+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_pipeline.py
[2022-10-27T14:20:44.361+0000] {task_command.py:384} INFO - Running <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T14:01:47.069341+00:00 [running]> on host 89b306621d74
[2022-10-27T14:20:45.023+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Luka Perkovic
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T14:01:47.069341+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T14:01:47.069341+00:00
[2022-10-27T14:20:51.345+0000] {logging_mixin.py:117} WARNING - /opt/***/dags/scripts/preprocess_data.py:36 FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
[2022-10-27T14:20:51.358+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/preprocess_data.py", line 36, in preprocess_data
    df = df.drop(*to_drop, axis=1)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
TypeError: drop() got multiple values for argument 'axis'
[2022-10-27T14:20:51.369+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=processing_data, execution_date=20221027T140147, start_date=20221027T142038, end_date=20221027T142051
[2022-10-27T14:20:51.396+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 59 for task processing_data (drop() got multiple values for argument 'axis'; 171)
[2022-10-27T14:20:51.500+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-27T14:20:51.638+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
