[2022-10-27T16:52:58.781+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T16:52:52.767227+00:00 [queued]>
[2022-10-27T16:52:58.843+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T16:52:52.767227+00:00 [queued]>
[2022-10-27T16:52:58.843+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T16:52:58.844+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-27T16:52:58.844+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T16:52:58.923+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): processing_data> on 2022-10-27 16:52:52.767227+00:00
[2022-10-27T16:52:58.930+0000] {standard_task_runner.py:54} INFO - Started process 200 to run task
[2022-10-27T16:52:59.054+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'processing_data', 'manual__2022-10-27T16:52:52.767227+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpecxn51ms']
[2022-10-27T16:52:59.056+0000] {standard_task_runner.py:83} INFO - Job 87: Subtask processing_data
[2022-10-27T16:52:59.057+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_pipeline.py
[2022-10-27T16:53:10.075+0000] {task_command.py:384} INFO - Running <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T16:52:52.767227+00:00 [running]> on host df91eb6f7666
[2022-10-27T16:53:10.439+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Luka Perkovic
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T16:52:52.767227+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T16:52:52.767227+00:00
[2022-10-27T16:53:20.734+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/preprocess_data.py", line 41, in preprocess_data
    save_file(pd.DataFrame(data=scaler.fit_transform(df), columns=df.columns), 'data_batch_transformed.csv')
  File "/opt/airflow/dags/scripts/handle_file.py", line 20, in save_file
    df.to_csv(os.path.join(DATA_DIR, file_name))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/data_batch_transformed.csv'
[2022-10-27T16:53:20.805+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=processing_data, execution_date=20221027T165252, start_date=20221027T165258, end_date=20221027T165320
[2022-10-27T16:53:20.825+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 87 for task processing_data ([Errno 13] Permission denied: '/opt/airflow/data/data_batch_transformed.csv'; 200)
[2022-10-27T16:53:20.861+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-27T16:53:20.942+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
